### ISSUE TITLE
fraphael.js does not pass jslint/jshint validation

### ISSUE THREAD

**Issue by dfrechette** [chrismichaelscott/fraphael#1]
When executing jshint against your code, it ends with a "too many errors" message. The cause is the simple. All conditions in the code that check for 'undefined' variables and parameters are using == or != operators. This is a weak coding practice. 

I modified the code on my side to fix the situation. The attached screen captures show you the type of the changes I made to address the problem.

Best regards

![screen shot 2013-09-05 at 15 00 14](https://f.cloud.github.com/assets/14079/1090817/93fa7328-165d-11e3-80dd-777048c38dec.png)
![screen shot 2013-09-05 at 15 00 23](https://f.cloud.github.com/assets/14079/1090818/9408629e-165d-11e3-9f75-239e20123e6b.png)
![screen shot 2013-09-05 at 15 00 46](https://f.cloud.github.com/assets/14079/1090819/940b880c-165d-11e3-93ad-33183b2d7e63.png)
![screen shot 2013-09-05 at 15 00 55](https://f.cloud.github.com/assets/14079/1090820/9405ea28-165d-11e3-8930-6aca441bc66f.png)

**Comment by dfrechette** [comment]
I also added the "use strict" directive to place the code in a “strict” operating context. 

<pre><code>...
// Create the global FRaphael object
(function(scope) {
    "use strict"; // http://ejohn.org/blog/ecmascript-5-strict-mode-json-and-more/
    var version = "0.0.1",
...
</code></pre>

**Comment by dfrechette** [comment]
Lastly, the "in" word is a reserved word in JS. Having an object property named 'in' causes yet more validation errors and possible JS errors at runtime. I modified the code to fix the problem. Take a look at the attached screen captures.

![screen shot 2013-09-05 at 15 39 15](https://f.cloud.github.com/assets/14079/1091125/05186c5e-1663-11e3-85ef-3d21d133ee15.png)

![screen shot 2013-09-05 at 15 37 18](https://f.cloud.github.com/assets/14079/1091114/c4adb7aa-1662-11e3-97eb-b9b6c25453d7.png)

**Comment by dfrechette** [comment]
Use the following link to validate the code by yourself: http://www.javascriptlint.com/online_lint.php

**Comment by chrismichaelscott** [comment]
Hi dfrechette,

Thanks for the comments. Much appreciated. If you issue a pull request I'll take most of those changes into the Master.

I'm not sure I agree with the `undefined` issue, though. The standard equality operator against `undefined` will check if a variable is `undefined` or `null`; the strict equality operator would just check for `undefined`; the way you have written the code would return true for `0`, `""`, `null`, `undefined`, etc. I am checking whether the values passed in are either null or undefined, so the correct test is the standard equality operator:

```
var x;
(!x); // returns true
(x == undefined); // returns true
(x === undefined); // returns true

var x = null;
(!x); // returns true
(x == undefined); // returns true
(x === undefined); // returns false

var x = "";
(!x); // returns true
(x == undefined); // returns false
(x === undefined); // returns false

var x = 0;
(!x); // returns true
(x == undefined); // returns false
(x === undefined); // returns false
```
