### ISSUE TITLE
Filters not available in IE9

### ISSUE THREAD

**Issue by SebTheBabe** [chrismichaelscott/fraphael#3]
Hello,

First, Many thanks for your plugin ! awesome 

I have a bug on IE (9), no filters are displayed... and it crashes my app...is there any known trouble with this ?

thanks for your answer.

**Comment by chrismichaelscott** [comment]
Hey,

Thanks for message. Unfortunately, IE 9 does not support SVG filters (http://caniuse.com/#search=svg filter). That said, crashing is not good! Can you create a demo on codepen.io (or something similar) and I'll try it out and make sure it degrades gracefully (if possible).

Cheers.

**Comment by SebTheBabe** [comment]
thanks.

oh fu... i misread the page.. just read the top of the page..snif... Do you think there is an alternative ? (However..blur is ok on IE9..?)

No more crash, the bug was in an other function...

And what about a grayscale preset on images/shapes in the plugin ?? it would be great ! :)

**Comment by chrismichaelscott** [comment]
Hey,

First off the good stuff...

I have added two new functions to Raphael elements, greyScale() and desaturate(n). I will document them when I get some time but here's an example of basic usage: http://jsfiddle.net/a8x6h4ub/1/ . I hope that helps.

In terms of IE9 I'm not really very knowledgeable and I've had a quick and unsuccessful play on Browserstack. Sorry I can't be more helpful but if you get any ideas please let me know.

**Comment by SebTheBabe** [comment]
Yeah thanks for this ! I'll have a look tomorrow ;-)
