### ISSUE TITLE
addEffect throws exception

### ISSUE THREAD

**Issue by hwanders** [chrismichaelscott/fraphael#4]
The method `FR.Filter.prototype.addEffect` iterates (for example when using `emboss()`) over the elements of an array by using `for (var x in children)`. If some framework or the application code has extended `Array.prototype` (as prototype.js does), this piece may fail with an exception from the browser, for example "Argument 1 of Node.appendChild is not an object".

Solutions: 
a) Add a property check right at the beginning of the for-loop

```
for (var x in children) {    
    if (!children.hasOwnProperty(x)) continue;
    ...
```

b) Use index-based iteration

```
for (var x=0; x<children.length; x++) {    
    ...
```

**Comment by chrismichaelscott** [comment]
Yes, good point. If you can create a pull request I will accept it otherwise I'll have a look this weekend.

Cheers.

**Comment by chrismichaelscott** [comment]
I have added the suggested solution ("a") - thanks for the prompt!
